In [2]:
with open("movies.txt",'r') as f:
    lines=f.readlines()

print(lines)

['Jaws,\n', ' The Avengers\n', 'Pitch perfect\n', 'Wasabi']


In [3]:
'&&'.join(lines)

'Jaws,\n&& The Avengers\n&&Pitch perfect\n&&Wasabi'

In [14]:
with open("movies.txt",'w') as f:
    f.write('Pulp Fiction\nThe avengers\nJuno')


In [15]:
with open("movies.txt",'r+') as f:
    f.read()
    f.write("\nJaws")


## `lower` and `upper`

In [16]:
s="Somebody once told me the world is gonna roll me"

In [17]:
s.lower()

'somebody once told me the world is gonna roll me'

In [18]:
s

'Somebody once told me the world is gonna roll me'

In [19]:
s.upper()

'SOMEBODY ONCE TOLD ME THE WORLD IS GONNA ROLL ME'

## `requests`

python module to access web pages

In [1]:
import requests

In [24]:
weblink="https://scassani.github.io/MTH337-F21/index.html"

r=requests.get(weblink)
r.status_code

200

In [29]:
requests.get('https://nytimes.com/tree')

<Response [404]>

In [31]:
webpage=r.text

In [32]:
webpage.find('Cassani')

6876

In [33]:
webpage[6876:7000]

'Cassani</div>\n<div class="line"><strong>Office:</strong> 321 Mathematics Building</div>\n<div class="line"><strong>E-mail:</s'

In [35]:
messagelink="https://scassani.github.io/MTH337-F21/_downloads/8bccfadb505510aa05b099010d542464/Wieclaw.txt"

message=requests.get(messagelink).text
print(message)

iee le  t i htimhnssdnr etfch dhfisnchli stre ntarfr iiiamntlbtae   i  nso eedtdr tfhsbymdfhi ye cdaptt   
uona reil.dnm e u ipfmreyiTpllomaotthal sra, uvrmeiia leclrad
o taastsebmnbhwrs eutemrnc e,eo fhmaiuwienufs
i atwbo twtn tedyrrn teaetesr, nente atpnbhefhp  eoey
simfoewwoc,
tvdgt oehatbeehexssha 
hdonir mi b
rrha hoehuseiasswnd adc rIhrepdattieiheatohd  de  rhgtyls lneyiehni oitnasmshmo oue
ie  ndwnaod,snotaieissssId oouonae syit . mei i eas i ns
ieerBcoo,gi, o otgalnpg
erhlntebcwr
ono  . eed riiy errecp lje irehwnbimfg aaona”,
awbintsa iy
 ohedanispehenio ij hlege
ot a ro,es sfw rtthi,eyiueheeesl aeesha- cn rienneessdn tmobg hrulhohdlo    u.stir er i pt chftthasoretiltadlm Bctbffahanl cieveoerr l
l rer s, iafu ndryvacslta esaer es.nrt hh  sl ete a ap v ,rleo tow  tf, vimeah i modr,t agnerreanieheefmdsnocyhsyeh db 
houhdt c. ti  stpnfgl o ’pop seasaopstetnng rn  elu v on
vydyh-nede p eeldhgyhoetlafww Iadihosg anao soalu;Inodaoeene ifnvptv  ttaanchertn oonin r n p emdtfiaetedri.mn

In [36]:
list(enumerate('hello'))

[(0, 'h'), (1, 'e'), (2, 'l'), (3, 'l'), (4, 'o')]

In [38]:
import numpy as np
a=np.arange(12).reshape(3,4)

In [39]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [40]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [41]:
a.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [2]:
imglink='http://www.buffalo.edu/content/shared/cas/math/faculty/cassani/jcr%3acontent/profileinfo.img.140.140.z.jpg/1598020383575.jpg'
r=requests.get(imglink)
r

<Response [200]>

In [5]:
img=r.content

In [6]:
with open('prof.png','wb') as f:
    f.write(img)

## dictionaries

In [9]:
d={'R':[1,0,0],'G':[0,1,0],'B':[0,0,1]}
d

{'R': [1, 0, 0], 'G': [0, 1, 0], 'B': [0, 0, 1]}

In [10]:
d['R']

[1, 0, 0]

In [11]:
d['Y']=[1,1,0] # adding an element
d

{'R': [1, 0, 0], 'G': [0, 1, 0], 'B': [0, 0, 1], 'Y': [1, 1, 0]}

In [12]:
'Y' in d

True

In [14]:
for k in d:
    print(k)

R
G
B
Y


In [15]:
for k in d.keys():
    print(k)

R
G
B
Y


In [17]:
for v in d.values():
    print(v)

[1, 0, 0]
[0, 1, 0]
[0, 0, 1]
[1, 1, 0]


In [18]:
for k,v in d.items():
    print(k,v)

R [1, 0, 0]
G [0, 1, 0]
B [0, 0, 1]
Y [1, 1, 0]


In [19]:
mylist=[['R',[1,0,0]],['G',[0,1,0]]]
dict(mylist)

{'R': [1, 0, 0], 'G': [0, 1, 0]}

In [20]:
d

{'R': [1, 0, 0], 'G': [0, 1, 0], 'B': [0, 0, 1], 'Y': [1, 1, 0]}

In [21]:
list(d.items())

[('R', [1, 0, 0]), ('G', [0, 1, 0]), ('B', [0, 0, 1]), ('Y', [1, 1, 0])]